class MedicalSpecializations {
  static const List<String> specializations = [
    'Allergist / Immunologist',
    'Anesthesiologist',
    'Andrologist',
    'Audiologist',
    'Bariatric Surgeon',
    'Cardiologist',
    'Cardiothoracic Surgeon',
    'Chiropractor',
    'Colorectal Surgeon (Proctologist)',
    'Critical Care Specialist (Intensivist)',
    'Dentist',
    'Dermatologist',
    'Diabetologist',
    'Emergency Medicine Specialist',
    'Endocrinologist',
    'ENT Specialist (Otolaryngologist)',
    'Epidemiologist',
    'Family Medicine Physician',
    'Forensic Pathologist',
    'Gastroenterologist',
    'General Physician',
    'General Surgeon',
    'Geneticist',
    'Geriatrician (Elderly Care Specialist)',
    'Gynecologist / Obstetrician',
    'Hand Surgeon',
    'Hematologist',
    'Hepatologist',
    'Homeopathic Doctor',
    'Infectious Disease Specialist',
    'Intensivist (Critical Care)',
    'Internal Medicine Specialist',
    'Interventional Radiologist',
    'Neonatologist',
    'Nephrologist',
    'Neurologist',
    'Neurosurgeon',
    'Nuclear Medicine Specialist',
    'Nutritionist / Dietitian',
    'Obstetrician (Pregnancy Specialist)',
    'Occupational Therapist',
    'Oncologist (Cancer Specialist)',
    'Ophthalmologist (Eye Specialist)',
    'Optometrist (Vision Specialist)',
    'Oral and Maxillofacial Surgeon',
    'Orthodontist',
    'Orthopedic Surgeon / Orthopedist',
    'Osteopath',
    'Pathologist',
    'Pediatrician (Child Specialist)',
    'Periodontist (Gum Specialist)',
    'Pharmacologist',
    'Physical Medicine & Rehabilitation Specialist (Physiatrist)',
    'Physiotherapist',
    'Plastic / Cosmetic Surgeon',
    'Podiatrist (Foot Specialist)',
    'Psychiatrist',
    'Psychologist',
    'Pulmonologist (Chest / Lung Specialist)',
    'Radiologist',
    'Rheumatologist',
    'Sexologist',
    'Sleep Medicine Specialist',
    'Speech Therapist',
    'Sports Medicine Specialist',
    'Thoracic Surgeon',
    'Transplant Surgeon',
    'Trauma Surgeon',
    'Urologist',
    'Vascular Surgeon',
    'Veterinary Doctor (Animal Specialist)',
  ];

  static List<String> searchSpecializations(String query) {
    if (query.isEmpty) return specializations;

    return specializations
        .where(
          (specialization) =>
              specialization.toLowerCase().contains(query.toLowerCase()),
        )
        .toList();
  }
}

class MedicalDegrees {
  static const List<String> degrees = [
    'MBBS',
    'BDS',
    'BHMS',
    'BAMS',
    'BUMS',
    'BNYS',
    'BVSc & AH',
    'MD',
    'MS',
    'MDS',
    'DM',
    'MCh',
    'DNB',
    'PhD (Medicine/Medical Research)',
  ];
}
